### ISSUE TITLE
Difference between `next-theme/hexo-optimize` and `theme-next/hexo-filter-optimize`

### ISSUE THREAD

**Issue by awwong1** [next-theme/hexo-optimize#6]
Hi @stevenjoezhang,

Why are there two repositories that do (almost) same thing?

* https://github.com/theme-next/hexo-filter-optimize
* https://github.com/next-theme/hexo-optimize

Can one of these repositories be archived?

**Comment by stevenjoezhang** [comment]
I don't have permission to archive hexo-filter-optimize, nor publish it on npm. So I created a new one.

**Comment by awwong1** [comment]
Thank you for the quick reply! I just discovered this project and it is a little bit confusing :sweat_smile: 

Have you reached out to any of the [theme-next people](https://github.com/orgs/theme-next/people), or to @tsanie who owns the other npm package?
I'm not sure if there is additional context to this that I am missing.

**Comment by stevenjoezhang** [comment]
It does not matter. I'm not interested in the development of hexo-filter-optimize. Maybe you can open an issue here: https://github.com/theme-next/hexo-filter-optimize
